{{- if .Values.envSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-chart.fullname" . }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.envSecret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
